{
  "openapi": "3.0.0",
  "info": {
    "title": "API",
    "description": "Challenge: TRACTIAN Back-End Software Engineer",
    "version": "1.0.0",
    "contact": {
      "name": "William Brito",
      "url": "https://github.com/williamrlbrito/",
      "email": "williamrldb@gmail.com"
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/accounts": {
      "post": {
        "tags": ["accounts"],
        "summary": "Create a new account",
        "description": "Create a new account",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "John Doe",
                  "email": "johndoe@gmail.com",
                  "password": "123456",
                  "password_confirmation": "123456"
                },
                "required": [
                  "name",
                  "email",
                  "password",
                  "password_confirmation"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                    "name": "John Doe",
                    "email": "johndoe@gmail.com",
                    "createdAt": "2022-01-06T23:37:27.518Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "User already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/accounts/authenticate": {
      "post": {
        "tags": ["accounts"],
        "summary": "Authenticate an account",
        "description": "Authenticate an account",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "email": "johndoe@gmail.com",
                  "password": "123456"
                },
                "required": ["email", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Username or password is incorrect"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/accounts/profile": {
      "get": {
        "tags": ["accounts"],
        "summary": "Get account profile",
        "description": "Get account profile",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "0bc918bf-f5ad-4fbc-b60d-b4a4a15fb9a8",
                    "name": "John Three",
                    "email": "johnthree@gmail.com",
                    "createdAt": "2022-01-07T22:06:26.536Z"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "tags": ["accounts"],
        "summary": "Update account profile",
        "description": "Update account profile",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "oldPassword": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "John Doe",
                  "oldPassword": "123456",
                  "password": "1234"
                },
                "required": ["name"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "0bc918bf-f5ad-4fbc-b60d-b4a4a15fb9a8",
                    "name": "John Three",
                    "email": "johndoe@gmail.com",
                    "createdAt": "2022-01-06T19:00:55.647Z"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/companies": {
      "post": {
        "tags": ["companies"],
        "summary": "Create a new company",
        "description": "Create a new company and associate it with the authenticated account",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "Company One"
                },
                "required": ["name"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                    "name": "Company One",
                    "createdAt": "2022-01-06T23:37:27.518Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Company already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "get": {
        "tags": ["companies"],
        "summary": "Get all companies",
        "description": "Get all companies associated with the authenticated account",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": [
                    {
                      "id": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                      "name": "Company One",
                      "createdAt": "2022-01-06T23:37:27.518Z"
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/units": {
      "post": {
        "tags": ["units"],
        "summary": "Create a new unit",
        "description": "Create a new unit for company",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyId": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "companyId": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                  "name": "Unit One"
                },
                "required": ["companyId", "name"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                    "name": "Unit One",
                    "createdAt": "2022-01-06T23:37:27.518Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Company does not exist | Unit already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "get": {
        "tags": ["units"],
        "summary": "Get all units",
        "description": "Get all units associated with the authenticated account",
        "parameters": [
          {
            "name": "companyId",
            "in": "query",
            "description": "Company ID",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": [
                    {
                      "id": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                      "name": "Unit One",
                      "createdAt": "2022-01-06T23:37:27.518Z"
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/assets": {
      "post": {
        "tags": ["assets"],
        "summary": "Create a new asset",
        "description": "Create a new asset for company",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "unityId": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "model": {
                    "type": "string"
                  },
                  "owner": {
                    "type": "string"
                  },
                  "status": {
                    "type": "number"
                  },
                  "healthLevel": {
                    "type": "number"
                  }
                },
                "example": {
                  "unityId": "daf480e9-ef0b-4a2c-bfce-849922acc291",
                  "name": "Asset One",
                  "description": "Asset description",
                  "model": "Asset model",
                  "owner": "Asset owner",
                  "status": "Running",
                  "healthLevel": 70
                },
                "required": [
                  "unityId",
                  "name",
                  "description",
                  "model",
                  "owner",
                  "status",
                  "healthLevel"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "model": {
                      "type": "string"
                    },
                    "owner": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "healthLevel": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "660eb8c5-be8e-40f7-b472-54faf8bf8ba8",
                    "name": "Asset One",
                    "description": "Asset description",
                    "model": "Asset model",
                    "owner": "Asset owner",
                    "status": "Running",
                    "healthLevel": 70,
                    "photoUrl": null,
                    "createdAt": "2022-01-07T19:32:06.089Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Unity or Company does not exist or you are not authorized | Asset already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "get": {
        "tags": ["assets"],
        "summary": "Get all assets",
        "description": "Get all assets associated with units associated with the authenticated account",
        "parameters": [
          {
            "name": "unityId",
            "in": "query",
            "description": "Unity Id",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "unityId": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "model": {
                      "type": "string"
                    },
                    "owner": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "healthLevel": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": [
                    {
                      "id": "660eb8c5-be8e-40f7-b472-54faf8bf8ba8",
                      "unityId": "daf480e9-ef0b-4a2c-bfce-849922acc291",
                      "name": "Asset One",
                      "description": "Asset description",
                      "model": "Asset model",
                      "owner": "Asset owner",
                      "status": "Running",
                      "healthLevel": 70,
                      "photoUrl": null,
                      "createdAt": "2022-01-07T19:32:06.089Z"
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/users": {
      "post": {
        "tags": ["users"],
        "summary": "Create a new user",
        "description": "Create a new user and associate it with the company",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyId": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "companyId": "daf480e9-ef0b-4a2c-bfce-849922acc291",
                  "name": "John Doe",
                  "email": "johndoe@gmail.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                    "name": "John Doe",
                    "email": "johndoe@gmail.com",
                    "createdAt": "2022-01-06T23:37:27.518Z"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Company does not exist or you are not authorized | User already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "get": {
        "tags": ["users"],
        "summary": "Get all users",
        "description": "Get all users associated with the authenticated account",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "createdAt": {
                      "type": "string"
                    }
                  },
                  "example": [
                    {
                      "id": "749a4edc-4df7-45fc-97cf-4265cac4598d",
                      "name": "John Doe",
                      "email": "johndoe@gmail.com",
                      "createdAt": "2022-01-06T23:37:27.518Z"
                    }
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "status": "error",
                    "message": "Internal server error"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    }
  }
}
